# -*- coding: utf-8 -*-
# Each palette: id, name, blurb, single grouping key 'c' (category).
P = {}

P['song'] = ("Song Elements","The parts a song is actually made of — sweep this when something feels missing.",{
"Rhythm & Time":["Pulse","Tempo","Meter","Time signature","Subdivision","Groove","Swing","Shuffle","Backbeat","Downbeat","Upbeat","Syncopation","Polyrhythm","Cross-rhythm","Hemiola","Rubato","Accelerando","Ritardando","Ostinato","Clave","Rhythmic motif","Anacrusis","Rest","Silence","Fermata","Tuplet","Metric modulation","Displacement","Push and pull","Pocket","Feel","Half-time","Double-time","Breakbeat","Drum fill","Roll","Flam","Ghost note","Accent pattern","Rhythmic unison"],
"Melody":["Motif","Theme","Phrase","Hook","Riff","Lick","Melodic contour","Range","Tessitura","Leap","Step","Passing tone","Neighbor tone","Appoggiatura","Suspension","Anticipation","Sequence","Inversion","Retrograde","Augmentation","Diminution","Call and response","Question and answer","Melisma","Syllabic setting","Ornament","Trill","Grace note","Slide","Bend","Vibrato","Blue note","Pickup","Cadential figure","Countermelody","Obbligato","Head","Solo","Improvisation","Quotation"],
"Harmony":["Key","Tonic","Dominant","Subdominant","Chord","Triad","Seventh chord","Extension","Voicing","Inversion","Bass line","Pedal point","Drone","Progression","Turnaround","Cadence","Modulation","Pivot chord","Borrowed chord","Secondary dominant","Tritone substitution","Suspension","Tension and release","Dissonance","Consonance","Chromaticism","Diatonicism","Modal interchange","Parallel harmony","Quartal harmony","Cluster","Power chord","Open fifth","Drone-based harmony","Static harmony","Harmonic rhythm","Reharmonization","Vamp","Loop","Changes"],
"Texture & Arrangement":["Monophony","Homophony","Polyphony","Heterophony","Density","Layering","Doubling","Unison","Octaves","Register spacing","Frequency range","Foreground","Midground","Background","Bed","Pad","Counterline","Fill","Stab","Riser","Drop","Build","Breakdown","Drop-out","Entrance","Exit","Instrumentation","Orchestration","Voicing spread","Panning","Stereo width","Depth","Space","Ensemble","Solo texture","Duet","Tutti","Sparse section","Wall of sound","Negative space"],
"Form & Structure":["Intro","Verse","Pre-chorus","Chorus","Post-chorus","Bridge","Middle eight","Refrain","Hook section","Instrumental","Solo section","Interlude","Breakdown","Outro","Coda","Tag","Fade-out","Cold ending","Strophic form","Binary form","Ternary form","Rondo","Sonata form","Theme and variations","Through-composed","Twelve-bar blues","AABA","Verse-chorus","Arch form","Suite","Movement","Section","Phrase length","Period","Sentence","Bar count","Odd-bar phrasing","Repeat","Contrast","Return"],
"Dynamics & Expression":["Volume","Dynamic range","Crescendo","Diminuendo","Swell","Accent","Sforzando","Attack","Decay","Sustain","Release","Articulation","Legato","Staccato","Marcato","Tenuto","Slur","Phrasing","Breath","Intensity curve","Climax","Anticlimax","Restraint","Release","Contrast","Terracing","Subito","Fade","Surge","Collapse"],
"Timbre & Tone":["Timbre","Tone color","Brightness","Warmth","Darkness","Grit","Purity","Noise content","Harmonic content","Overtones","Formants","Transient","Body","Air","Presence","Edge","Roundness","Nasality","Breathiness","Rasp","Growl","Shimmer","Dullness","Sheen","Bite","Weight","Thinness","Fullness","Hollowness","Character"],
"Lyrics & Voice":["Subject","Point of view","Narrator","Persona","Imagery","Metaphor","Refrain","Rhyme scheme","Internal rhyme","Slant rhyme","Meter of the line","Scansion","Syllable count","Prosody","Word stress","Vowel color","Consonant texture","Repetition","Hook line","Title line","Payoff line","Turn","Volta","Narrative arc","Detail","Abstraction","Direct address","Ambiguity","Vernacular","Silence in the lyric"],
})

P['emotion'] = ("Emotions","Aim at one and let the arrangement serve it. Mixed states are usually the interesting ones.",{
"Joy & Elation":["Joy","Delight","Glee","Elation","Euphoria","Jubilation","Exuberance","Giddiness","Cheer","Buoyancy","Playfulness","Mirth","Amusement","Triumph","Pride","Satisfaction","Contentment","Gratitude","Relief","Hope","Optimism","Anticipation","Excitement","Thrill","Rapture","Bliss","Serenity","Ease","Warmth","Affection"],
"Sadness & Grief":["Sadness","Sorrow","Grief","Mourning","Melancholy","Wistfulness","Nostalgia","Homesickness","Longing","Yearning","Regret","Remorse","Guilt","Shame","Disappointment","Dejection","Despondency","Despair","Hopelessness","Emptiness","Numbness","Loneliness","Isolation","Abandonment","Heartbreak","Anguish","Devastation","Resignation","Weariness","Defeat"],
"Anger & Defiance":["Anger","Rage","Fury","Wrath","Indignation","Outrage","Resentment","Bitterness","Spite","Contempt","Scorn","Disdain","Disgust","Revulsion","Irritation","Annoyance","Frustration","Exasperation","Impatience","Hostility","Aggression","Vengefulness","Defiance","Rebellion","Stubbornness","Righteousness","Jealousy","Envy","Betrayal","Grievance"],
"Fear & Unease":["Fear","Terror","Panic","Horror","Dread","Anxiety","Worry","Apprehension","Nervousness","Tension","Foreboding","Paranoia","Suspicion","Distrust","Insecurity","Vulnerability","Helplessness","Powerlessness","Claustrophobia","Vertigo","Alarm","Startle","Unease","Disquiet","Restlessness","Agitation","Doubt","Hesitance","Timidity","Cowardice"],
"Love & Connection":["Love","Adoration","Devotion","Tenderness","Intimacy","Closeness","Trust","Loyalty","Compassion","Empathy","Sympathy","Kindness","Care","Protectiveness","Belonging","Kinship","Camaraderie","Solidarity","Forgiveness","Acceptance","Desire","Passion","Lust","Infatuation","Attraction","Flirtation","Tenderness","Reverence","Admiration","Devotion"],
"Awe & Wonder":["Awe","Wonder","Amazement","Astonishment","Marvel","Reverence","Transcendence","Sublimity","Mystery","Curiosity","Fascination","Enchantment","Spellbound","Humility","Smallness","Vastness","Epiphany","Revelation","Clarity","Illumination","Ecstasy","Rapture","Sacredness","Solemnity","Piety","Devotion","Surrender","Openness","Presence","Stillness"],
"Calm & Stillness":["Calm","Peace","Tranquility","Stillness","Quiet","Repose","Rest","Comfort","Safety","Security","Softness","Gentleness","Patience","Acceptance","Equanimity","Detachment","Meditation","Reverie","Daydream","Drowsiness","Lull","Suspension","Weightlessness","Floating","Drift","Solitude","Privacy","Sanctuary","Refuge","Home"],
"Complex & Mixed":["Bittersweetness","Saudade","Hiraeth","Sehnsucht","Ambivalence","Conflictedness","Irony","Sardonicism","Cynicism","Absurdity","Dark humor","Gallows humor","Uncanniness","Dissociation","Alienation","Estrangement","Restless joy","Anxious hope","Grateful grief","Angry love","Tender rage","Joyful sorrow","Peaceful dread","Nervous excitement","Guilty pleasure","Reluctant admiration","Fond contempt","Hollow triumph","Sweet revenge","Willed indifference"],
})

P['theory'] = ("Theory Concepts","Reach for one you don't normally use. Constraint beats inspiration.",{
"Scales & Modes":["Major scale","Natural minor","Harmonic minor","Melodic minor","Ionian","Dorian","Phrygian","Lydian","Mixolydian","Aeolian","Locrian","Lydian dominant","Altered scale","Phrygian dominant","Harmonic major","Double harmonic","Hungarian minor","Neapolitan","Whole tone","Octatonic","Diminished scale","Chromatic scale","Major pentatonic","Minor pentatonic","Blues scale","Bebop scale","Hirajoshi","In scale","Insen","Yo scale","Raga","Maqam","Hijaz","Rast","Bayati","Slendro","Pelog","Acoustic scale","Overtone scale","Synthetic scale"],
"Chords & Voicings":["Major triad","Minor triad","Diminished triad","Augmented triad","Major seventh","Dominant seventh","Minor seventh","Half-diminished","Fully diminished","Minor-major seventh","Sixth chord","Ninth chord","Eleventh chord","Thirteenth chord","Add9","Sus2","Sus4","Altered dominant","Slash chord","Power chord","Quartal voicing","Quintal voicing","Cluster","Drop 2","Drop 3","Rootless voicing","Shell voicing","Close position","Open position","Spread voicing","Upper structure triad","Polychord","Hybrid chord","Voice leading","Common tone","Inversion","First inversion","Second inversion","Figured bass","Chord symbol"],
"Harmony & Function":["Tonic function","Dominant function","Subdominant function","Authentic cadence","Plagal cadence","Half cadence","Deceptive cadence","Phrygian cadence","Picardy third","Circle of fifths","Diatonic function","Secondary dominant","Secondary leading-tone","Tritone substitution","Backdoor dominant","Neapolitan sixth","Augmented sixth","Italian sixth","French sixth","German sixth","Modal interchange","Borrowed chord","Chromatic mediant","Common-tone modulation","Pivot modulation","Direct modulation","Sequential modulation","Tonicization","Prolongation","Pedal point","Passing chord","Neighbor chord","Planing","Parallel motion","Contrary motion","Oblique motion","Similar motion","Functional ambiguity","Modal harmony","Non-functional harmony"],
"Rhythm & Meter":["Simple meter","Compound meter","Duple meter","Triple meter","Quadruple meter","Asymmetric meter","Additive rhythm","Divisive rhythm","Polymeter","Polyrhythm","Cross-rhythm","Hemiola","Tuplet","Triplet","Quintuplet","Syncopation","Anticipation","Suspension of pulse","Metric modulation","Tempo modulation","Isorhythm","Talea","Color","Tala","Rhythmic cycle","Clave","Tresillo","Cinquillo","Son clave","Rumba clave","Bell pattern","Shuffle feel","Swing ratio","Straight eighths","Groove template","Micro-timing","Rubato","Free time","Ametric","Pulse ambiguity"],
"Counterpoint & Line":["Species counterpoint","Cantus firmus","Imitation","Canon","Round","Fugue","Subject","Answer","Countersubject","Exposition","Episode","Stretto","Augmentation","Diminution","Inversion","Retrograde","Retrograde inversion","Invertible counterpoint","Double counterpoint","Parallel fifths","Parallel octaves","Voice crossing","Voice overlap","Suspension chain","Passing tone","Neighbor tone","Escape tone","Anticipation","Pedal tone","Cambiata","Free counterpoint","Homorhythm","Heterophony","Melodic independence","Contrapuntal density","Obbligato","Descant","Ground bass","Chaconne","Passacaglia"],
"Form & Process":["Motif development","Thematic transformation","Variation","Ostinato","Riff-based form","Additive process","Phase music","Minimalism","Serialism","Tone row","Twelve-tone technique","Set theory","Pitch class","Interval class","Aleatoric process","Indeterminacy","Graphic score","Modular form","Open form","Moment form","Golden section","Arch form","Palindrome","Retrograde form","Fractal structure","Layer accumulation","Subtractive arrangement","Terraced dynamics","Textural form","Timbral form"],
"Tuning & Systems":["Equal temperament","Just intonation","Pythagorean tuning","Meantone temperament","Well temperament","Microtonality","Quarter tone","Comma","Syntonic comma","Pythagorean comma","Cent","Harmonic series","Overtone","Undertone","Partial","Beating","Difference tone","Combination tone","Spectralism","Xenharmonic","19-tone","31-tone","53-tone","Bohlen-Pierce","Scordatura","Open tuning","Drop tuning","Alternate tuning","Sympathetic resonance","Inharmonicity"],
})

P['genre'] = ("Genres","Not to copy — to steal one gesture from.",{
"Rock & Guitar":["Rock and roll","Blues rock","Hard rock","Psychedelic rock","Progressive rock","Art rock","Glam rock","Punk rock","Post-punk","New wave","Goth rock","Indie rock","Alternative rock","Grunge","Shoegaze","Dream pop","Noise rock","Math rock","Post-rock","Emo","Screamo","Garage rock","Surf rock","Southern rock","Heartland rock","Stoner rock","Krautrock","Space rock","Slowcore","Midwest emo"],
"Metal":["Heavy metal","Thrash metal","Death metal","Black metal","Doom metal","Sludge metal","Power metal","Speed metal","Progressive metal","Symphonic metal","Folk metal","Viking metal","Gothic metal","Nu metal","Metalcore","Deathcore","Grindcore","Djent","Post-metal","Drone metal","Atmospheric black metal","Blackgaze","Technical death metal","Melodic death metal","Industrial metal","Groove metal","Avant-garde metal","Funeral doom","Stoner metal","Neoclassical metal"],
"Electronic":["House","Deep house","Tech house","Acid house","Techno","Detroit techno","Minimal techno","Trance","Psytrance","Drum and bass","Jungle","Breakbeat","Dubstep","Garage","UK garage","Grime","Footwork","Juke","Hardcore","Gabber","Ambient","Dark ambient","Drone","IDM","Glitch","Downtempo","Trip hop","Chillwave","Vaporwave","Synthwave","Electro","Italo disco","Nu disco","EBM","Industrial","Noise","Musique concrète","Acousmatic","Modular","Generative music"],
"Hip-Hop & R&B":["Hip-hop","Boom bap","Trap","Drill","Cloud rap","Conscious hip-hop","Gangsta rap","G-funk","Jazz rap","Lo-fi hip-hop","Abstract hip-hop","Horrorcore","Crunk","Bounce","Hyphy","Phonk","R&B","Contemporary R&B","Neo-soul","Alternative R&B","Quiet storm","New jack swing","Soul","Northern soul","Southern soul","Funk","P-funk","Go-go","Disco","Boogie"],
"Jazz & Improvised":["Ragtime","Dixieland","Swing","Big band","Bebop","Hard bop","Cool jazz","Modal jazz","Free jazz","Avant-garde jazz","Post-bop","Soul jazz","Jazz fusion","Jazz funk","Latin jazz","Afro-Cuban jazz","Bossa nova","Gypsy jazz","Third stream","Spiritual jazz","Nu jazz","Acid jazz","Chamber jazz","Ethio-jazz","Free improvisation","Vocalese","Scat","Stride","Boogie-woogie","Smooth jazz"],
"Folk & Country":["Folk","Traditional folk","Contemporary folk","Folk revival","Freak folk","Anti-folk","Americana","Country","Classic country","Outlaw country","Country pop","Alt-country","Bluegrass","Old-time","Appalachian","Cajun","Zydeco","Western swing","Honky-tonk","Bakersfield sound","Nashville sound","Gospel","Bluegrass gospel","Sea shanty","Murder ballad","Protest song","Singer-songwriter","Chamber folk","Psych folk","Celtic"],
"Classical & Art":["Medieval","Gregorian chant","Renaissance","Baroque","Classical period","Romantic","Late Romantic","Impressionism","Expressionism","Neoclassicism","Serialism","Minimalism","Post-minimalism","Spectralism","Musique concrète","Electroacoustic","Aleatoric","New Complexity","Neo-Romanticism","Sacred choral","Opera","Oratorio","Lieder","Chamber music","Symphony","Concerto","Film score","Ambient classical","Modern classical","Holy minimalism"],
"Global & Traditional":["Reggae","Ska","Rocksteady","Dub","Dancehall","Reggaeton","Salsa","Son cubano","Mambo","Cha-cha-chá","Bolero","Bachata","Merengue","Cumbia","Vallenato","Tango","Samba","Bossa nova","Forró","MPB","Tropicália","Afrobeat","Afrobeats","Highlife","Soukous","Mbalax","Desert blues","Gnawa","Rai","Chaabi","Fado","Flamenco","Rebetiko","Klezmer","Balkan brass","Turkish classical","Persian classical","Hindustani classical","Carnatic","Qawwali","Bhangra","Filmi","Gamelan","Gagaku","Enka","J-pop","K-pop","Mongolian throat singing","Tuvan khoomei","Joik"],
"Pop & Song":["Pop","Synth-pop","Dance-pop","Electropop","Bedroom pop","Hyperpop","Art pop","Baroque pop","Sunshine pop","Power pop","Jangle pop","Twee pop","Yacht rock","Soft rock","Adult contemporary","Chanson","Schlager","Bubblegum","Teen pop","City pop","Lounge","Exotica","Easy listening","Musical theatre","Cabaret","Vaudeville","Torch song","Standard","Novelty song","Jingle"],
})

P['texture'] = ("Textures & Adjectives","Say the sound before you name the plugin. Chase the word.",{
"Tactile":["Rough","Smooth","Coarse","Silky","Velvety","Furry","Fuzzy","Prickly","Spiky","Jagged","Serrated","Gritty","Sandy","Grainy","Powdery","Chalky","Waxy","Slick","Greasy","Oily","Sticky","Tacky","Gummy","Rubbery","Leathery","Papery","Crumbly","Flaky","Bristly","Downy","Woolly","Scratchy","Abrasive","Polished","Burnished","Pitted","Cracked","Ribbed","Knurled","Glassy"],
"Wet & Dry":["Wet","Damp","Moist","Soggy","Sodden","Drenched","Dripping","Slimy","Slippery","Viscous","Syrupy","Gooey","Sludgy","Watery","Fluid","Liquid","Molten","Dry","Arid","Parched","Dusty","Brittle","Crisp","Crunchy","Papery-dry","Bone-dry","Desiccated","Withered","Evaporated","Airless"],
"Temperature":["Hot","Scorching","Blistering","Searing","Molten","Smoldering","Warm","Balmy","Tepid","Lukewarm","Cool","Chilly","Cold","Frigid","Icy","Glacial","Frozen","Frosty","Crystalline","Bitter","Burning","Feverish","Sweltering","Humid","Clammy","Crisp","Brisk","Numbing","Thawing","Sunlit"],
"Weight & Density":["Heavy","Leaden","Dense","Thick","Solid","Massive","Ponderous","Bulky","Weighty","Compact","Packed","Saturated","Light","Airy","Weightless","Feathery","Gossamer","Thin","Sparse","Hollow","Empty","Porous","Diffuse","Wispy","Fragile","Delicate","Brittle","Sturdy","Robust","Dense-packed"],
"Brightness & Color":["Bright","Brilliant","Glaring","Blinding","Radiant","Luminous","Glowing","Shimmering","Sparkling","Glittering","Gleaming","Iridescent","Pearlescent","Golden","Silvery","Brassy","Coppery","Rusty","Dull","Matte","Muted","Muddy","Murky","Dim","Dusky","Shadowy","Dark","Inky","Pitch-black","Opaque"],
"Motion":["Flowing","Gliding","Drifting","Floating","Rolling","Undulating","Pulsing","Throbbing","Churning","Swirling","Spiraling","Tumbling","Cascading","Surging","Rushing","Racing","Darting","Lurching","Staggering","Jerky","Stuttering","Halting","Frozen","Static","Suspended","Hovering","Creeping","Crawling","Slithering","Bouncing"],
"Sharpness & Edge":["Sharp","Keen","Piercing","Cutting","Slicing","Stabbing","Biting","Nipping","Blunt","Dull-edged","Round","Rounded","Soft-edged","Blurred","Smeared","Fuzzy-edged","Crisp-edged","Defined","Precise","Clean","Ragged","Torn","Frayed","Splintered","Shattered","Chipped","Worn","Eroded","Smoothed","Sanded"],
"Age & Decay":["Ancient","Antique","Aged","Weathered","Faded","Bleached","Yellowed","Tarnished","Corroded","Rusted","Mouldering","Rotting","Decaying","Crumbling","Ruined","Derelict","Abandoned","Dusty","Cobwebbed","Fossilized","Petrified","Preserved","Pristine","New","Fresh","Raw","Unfinished","Virgin","Untouched","Newborn"],
"Space & Air":["Vast","Cavernous","Yawning","Boundless","Open","Expansive","Distant","Faraway","Near","Intimate","Close","Cramped","Tight","Claustrophobic","Enclosed","Sealed","Underground","Submerged","Airborne","Lofty","Towering","Shallow","Deep","Bottomless","Echoing","Reverberant","Dead","Dry-roomed","Muffled","Smothered"],
})

P['abstract'] = ("Abstract Nouns","The thing the song is secretly about.",{
"Time & Change":["Time","Duration","Moment","Eternity","Impermanence","Transience","Decay","Renewal","Cycle","Repetition","Return","Departure","Beginning","Ending","Threshold","Transition","Becoming","Erosion","Growth","Ruin","Progress","Stagnation","Delay","Urgency","Patience","Anniversary","Season","Youth","Age","Legacy"],
"Memory & Knowing":["Memory","Forgetting","Recollection","Nostalgia","Amnesia","Trace","Residue","Echo","Imprint","Record","Witness","Testimony","Knowledge","Ignorance","Understanding","Insight","Intuition","Doubt","Certainty","Belief","Confusion","Clarity","Revelation","Secret","Confession","Rumor","Myth","History","Inheritance","Ancestry"],
"Desire & Will":["Desire","Longing","Hunger","Thirst","Craving","Appetite","Ambition","Aspiration","Drive","Motivation","Will","Resolve","Determination","Discipline","Temptation","Indulgence","Restraint","Denial","Sacrifice","Compromise","Choice","Decision","Hesitation","Commitment","Obsession","Addiction","Devotion","Surrender","Refusal","Persistence"],
"Power & Order":["Power","Authority","Control","Dominance","Submission","Freedom","Bondage","Autonomy","Dependence","Hierarchy","Equality","Justice","Injustice","Law","Rebellion","Revolution","Order","Chaos","Structure","Anarchy","Discipline","Punishment","Mercy","Judgment","Guilt","Innocence","Corruption","Integrity","Duty","Obligation"],
"Bond & Distance":["Love","Friendship","Kinship","Community","Belonging","Solidarity","Loyalty","Betrayal","Trust","Suspicion","Intimacy","Distance","Estrangement","Reconciliation","Forgiveness","Grudge","Debt","Gift","Exchange","Obligation","Hospitality","Exile","Homecoming","Migration","Displacement","Refuge","Home","Threshold","Stranger","Neighbor"],
"Truth & Illusion":["Truth","Lie","Deception","Illusion","Mask","Facade","Performance","Authenticity","Pretense","Irony","Paradox","Contradiction","Ambiguity","Meaning","Nonsense","Absurdity","Symbol","Metaphor","Reality","Dream","Fantasy","Delusion","Hallucination","Mirage","Reflection","Shadow","Double","Identity","Anonymity","Reputation"],
"Spirit & Mystery":["Faith","Doubt","Grace","Sin","Redemption","Salvation","Damnation","Prayer","Ritual","Sacrament","Blessing","Curse","Prophecy","Fate","Destiny","Chance","Luck","Providence","Miracle","Omen","Soul","Spirit","Transcendence","Immanence","Sacredness","Profanity","Pilgrimage","Vision","Silence","Mystery"],
"Loss & Ruin":["Loss","Absence","Void","Emptiness","Lack","Hunger","Grief","Mourning","Death","Mortality","Oblivion","Erasure","Disappearance","Abandonment","Neglect","Isolation","Loneliness","Alienation","Exile","Defeat","Failure","Collapse","Catastrophe","Wound","Scar","Trauma","Healing","Survival","Endurance","Resilience"],
})

P['production'] = ("Production & Sound","The other half of the arrangement — what happens after the notes.",{
"Space & Reverb":["Room","Hall","Chamber","Plate reverb","Spring reverb","Convolution reverb","Shimmer reverb","Gated reverb","Reverse reverb","Pre-delay","Decay time","Early reflections","Diffusion","Damping","Dry signal","Wet signal","Send","Return","Ambience","Bloom","Tail","Nonlinear reverb","Cathedral","Cave","Bathroom","Stairwell","Outdoor","Close-miked","Far-miked","Distant perspective"],
"Time & Delay":["Slapback","Tape delay","Digital delay","Analog delay","Ping-pong delay","Multi-tap delay","Dotted eighth delay","Triplet delay","Feedback","Modulated delay","Reverse delay","Granular delay","Freeze","Looper","Stutter","Beat repeat","Glitch","Time stretch","Pitch shift","Varispeed","Tape wow","Flutter","Doppler","Echo chamber","Dub delay","Sidechained delay","Ducked delay","Filtered delay","Diffused delay","Infinite feedback"],
"Modulation":["Chorus","Flanger","Phaser","Tremolo","Vibrato","Rotary speaker","Leslie","Ring modulation","Frequency shifter","Auto-pan","Univibe","Ensemble","Doubler","Detune","Unison spread","LFO","Envelope follower","Sample and hold","Wobble","Warble","Pitch drift","Chorusing","Comb filter","Barber-pole","Through-zero flanging","Harmonic tremolo","Amplitude modulation","Cross modulation","Sync modulation","Random modulation"],
"Dynamics & Drive":["Compression","Limiting","Expansion","Gating","Transient shaping","Attack time","Release time","Ratio","Threshold","Knee","Makeup gain","Sidechain","Ducking","Pumping","Parallel compression","Bus compression","Multiband compression","Saturation","Overdrive","Distortion","Fuzz","Bitcrushing","Sample-rate reduction","Clipping","Soft clipping","Tape saturation","Tube warmth","Transformer colour","Harmonic exciter","Waveshaping"],
"Frequency & Tone":["EQ","High-pass filter","Low-pass filter","Band-pass filter","Notch filter","Shelf","Bell curve","Resonance","Cutoff","Formant filter","Wah","Auto-wah","Envelope filter","Vocal filter","Telephone filter","Lo-fi filter","Tilt EQ","Dynamic EQ","De-esser","Mud","Boxiness","Harshness","Sibilance","Air band","Presence band","Low-mid buildup","Sub bass","Rumble","Hiss","Noise floor"],
"Stereo & Field":["Panning","Stereo width","Mid-side","Mono compatibility","Haas effect","Stereo spread","Auto-pan","Binaural","Ambisonic","Surround","Immersive mix","Depth","Front-to-back","Layer placement","Center image","Phantom center","Phase","Polarity","Correlation","Comb filtering","Wide reverb","Narrow reverb","Hard pan","Static image","Moving image","Rotation","Collapse","Widening","Narrowing","Focus"],
"Synthesis & Sampling":["Subtractive synthesis","Additive synthesis","FM synthesis","Wavetable synthesis","Granular synthesis","Physical modelling","Sample playback","Vector synthesis","Phase distortion","Karplus-Strong","Oscillator","Sub oscillator","Noise generator","Filter envelope","Amplitude envelope","ADSR","Portamento","Glide","Unison","Voice stealing","Arpeggiator","Sequencer","Step sequencer","Sampler","Slicing","Chopping","Time-stretching","Reversal","Layering","Round-robin"],
"Recording & Capture":["Microphone placement","Close-miking","Room miking","Spot mic","Overhead","Stereo pair","XY","ORTF","Blumlein","Mid-side miking","Ribbon mic","Condenser","Dynamic mic","Contact mic","Hydrophone","Field recording","Foley","Ambience recording","Direct injection","Re-amping","Amp simulation","Tape machine","Multitrack","Overdub","Punch-in","Comping","Bleed","Headphone mix","Click track","Live take"],
})
