# -*- coding: utf-8 -*-
# Only the ones where the plain word wouldn't land on the right article.
# Everything else defaults to the item name; the page's search fallback fixes misses.
W={
# theory
"Chord":"Chord (music)","Triad":"Triad (music)","Extension":"Extended chord",
"Seventh chord":"Seventh chord","Major seventh":"Major seventh chord","Dominant seventh":"Dominant seventh chord",
"Minor seventh":"Minor seventh chord","Half-diminished":"Half-diminished seventh chord",
"Fully diminished":"Diminished seventh chord","Diminished seventh":"Diminished seventh chord",
"Minor-major seventh":"Minor major seventh chord","Sixth chord":"Sixth chord","Add9":"Added tone chord",
"Sus2":"Suspended chord","Sus4":"Suspended chord","Suspended chord":"Suspended chord",
"Ninth chord":"Ninth chord","Eleventh chord":"Eleventh chord","Thirteenth chord":"Thirteenth chord",
"Voicing":"Voicing (music)","Inversion":"Inversion (music)","Root position":"Root position",
"Cluster":"Tone cluster","Cluster voicing":"Tone cluster","Planing":"Parallel harmony",
"Guide tones":"Guide tone","Divisi":"Divisi","Doubling":"Doubling (music)",
"Key":"Key (music)","Tonic":"Tonic (music)","Dominant":"Dominant (music)","Subdominant":"Subdominant",
"Cadence":"Cadence","Modulation":"Modulation (music)","Tonicization":"Tonicization",
"Sequence":"Sequence (music)","Range":"Range (music)","Leap":"Steps and skips","Step":"Steps and skips",
"Phrase":"Phrase (music)","Motif":"Motif (music)","Theme":"Subject (music)","Hook":"Hook (music)",
"Riff":"Ostinato","Lick":"Lick (music)","Ornament":"Ornament (music)","Trill":"Trill (music)",
"Bend":"Bending (guitar)","Slide":"Glissando","Rest":"Rest (music)","Accent":"Accent (music)",
"Meter":"Metre (music)","Pulse":"Pulse (music)","Groove":"Groove (music)","Swing":"Swing (jazz performance style)",
"Feel":"Groove (music)","Pocket":"Groove (music)","Roll":"Drum roll","Flam":"Drum rudiment",
"Form":"Musical form","Section":"Section (music)","Period":"Period (music)","Sentence":"Sentence (music)",
"Contrast":"Musical development","Return":"Recapitulation (music)","Repeat":"Repeat sign",
"Bed":"Backing track","Pad":"Pad (music)","Fill":"Fill (music)","Stab":"Stab (music)",
"Drop":"Drop (music)","Build":"Build (music)","Breakdown":"Breakdown (music)","Vamp":"Vamp (music)",
"Loop":"Loop (music)","Changes":"Chord progression","Head":"Head (music)","Solo":"Solo (music)",
"Air":"Presence (sound recording)","Body":"Timbre","Edge":"Timbre","Character":"Timbre",
"Scordatura":"Scordatura","Comma":"Comma (music)","Cent":"Cent (music)","Partial":"Harmonic",
"Colour":"Isorhythm","Color":"Isorhythm","Talea":"Isorhythm","Tala":"Tala (music)",
"Clave":"Clave (rhythm)","Silence":"Silence in music","Density":"Texture (music)",
"Layering":"Texture (music)","Unison":"Unison","Octaves":"Octave","Space":"Reverberation",
"Subject":"Subject (music)","Answer":"Fugue","Episode":"Fugue","Exposition":"Sonata form",
"Variation":"Variation (music)","Canon":"Canon (music)","Round":"Round (music)",
"Prosody":"Prosody (music)","Scansion":"Scansion","Turn":"Turn (music)","Volta":"Volta (literature)",
"Refrain":"Refrain","Imagery":"Imagery","Metaphor":"Metaphor","Ambiguity":"Ambiguity",
"Breath":"Breathing (music)","Attack":"Envelope (music)","Decay":"Envelope (music)",
"Sustain":"Sustain","Release":"Envelope (music)","Intensity curve":"Dynamics (music)",
"Climax":"Climax (narrative)","Volume":"Loudness","Fade":"Fade (audio engineering)",
# production
"Room":"Reverberation","Hall":"Reverberation","Chamber":"Echo chamber","Bloom":"Reverberation",
"Tail":"Reverberation","Cave":"Reverberation","Stairwell":"Reverberation","Bathroom":"Reverberation",
"Feedback":"Audio feedback","Chorus":"Chorus effect","Flanger":"Flanging","Phaser":"Phaser (effect)",
"Tremolo":"Tremolo","Vibrato":"Vibrato","Leslie":"Leslie speaker","Ensemble":"Chorus effect",
"Doubler":"Double tracking","Detune":"Detuning","LFO":"Low-frequency oscillation",
"Wobble":"Dubstep","Warble":"Wow and flutter","Compression":"Dynamic range compression",
"Limiting":"Limiter","Expansion":"Expander (audio)","Gating":"Noise gate","Ratio":"Dynamic range compression",
"Threshold":"Dynamic range compression","Knee":"Dynamic range compression","Sidechain":"Sidechain compression",
"Ducking":"Ducking","Pumping":"Dynamic range compression","Saturation":"Harmonic distortion",
"Overdrive":"Distortion (music)","Distortion":"Distortion (music)","Fuzz":"Distortion (music)",
"Clipping":"Clipping (audio)","Crunch":"Distortion (music)","Grit":"Distortion (music)",
"EQ":"Equalization (audio)","Shelf":"Equalization (audio)","Resonance":"Resonance","Cutoff":"Cutoff frequency",
"Q factor":"Q factor","Wah":"Wah-wah pedal","Sibilance":"Sibilant","Mud":"Equalization (audio)",
"Panning":"Panning (audio)","Phase":"Phase (waves)","Polarity":"Absolute polarity",
"Depth":"Sound localization","Perspective":"Sound localization","Proximity":"Proximity effect (audio)",
"Reverse":"Reverse (audio)","Scrub":"Scrubbing (audio)","Oscillator":"Electronic oscillator",
"Glide":"Portamento","Unison":"Unison","Polyphony":"Polyphony and monophony in instruments",
"Monophony":"Polyphony and monophony in instruments","Sampler":"Sampler (musical instrument)",
"Slicing":"Sampling (music)","Chopping":"Sampling (music)","One-shot":"Sampling (music)",
"Take":"Take (filmmaking)","Bleed":"Microphone bleed","Console":"Mixing console","Preamp":"Preamplifier",
"Bus":"Bus (audio)","Group":"Bus (audio)","Insert":"Insert (effects processing)","Stem":"Stem (audio)",
"Solo":"Mixing console","Mute":"Mixing console","Fader":"Fader (audio engineering)",
"Level":"Gain (electronics)","Balance":"Audio mixing","Loudness":"Loudness","LUFS":"LKFS",
"Dithering":"Dither","Hum":"Mains hum","Buzz":"Mains hum","Glitch":"Glitch (music)",
"Stutter":"Stutter edit","Aliasing":"Aliasing","Riser":"Build (music)","Impact":"Sound effect",
# genres — the ones that collide with ordinary words
"House":"House music","Techno":"Techno","Trance":"Trance music","Garage":"UK garage",
"Grime":"Grime (music genre)","Jungle":"Jungle music","Hardcore":"Hardcore techno",
"Drill":"Drill music","Trap":"Trap music","Bounce":"Bounce music","Crunk":"Crunk",
"Soul":"Soul music","Funk":"Funk","Disco":"Disco","Swing":"Swing music","Bebop":"Bebop",
"Folk":"Folk music","Country":"Country music","Gospel":"Gospel music","Pop":"Pop music",
"Rock":"Rock music","Metal":"Heavy metal music","Punk":"Punk rock","Emo":"Emo","Ska":"Ska",
"Dub":"Dub music","Reggae":"Reggae","Salsa":"Salsa music","Samba":"Samba","Tango":"Tango music",
"Cumbia":"Cumbia","Fado":"Fado","Flamenco":"Flamenco","Klezmer":"Klezmer","Highlife":"Highlife",
"Soukous":"Soukous","Enka":"Enka","Filmi":"Filmi","Qawwali":"Qawwali","Bhangra":"Bhangra",
"Gamelan":"Gamelan","Gagaku":"Gagaku","Joik":"Yoik","Standard":"Jazz standard",
"Lounge":"Lounge music","Exotica":"Exotica","Cabaret":"Cabaret","Vaudeville":"Vaudeville",
"Minimalism":"Minimal music","Serialism":"Serialism","Baroque":"Baroque music",
"Romantic":"Romantic music","Impressionism":"Impressionism in music","Opera":"Opera",
"Symphony":"Symphony","Concerto":"Concerto","Ambient":"Ambient music","Drone":"Drone music",
"Noise":"Noise music","Industrial":"Industrial music","Electro":"Electro (music)",
"Breakbeat":"Breakbeat","Footwork":"Footwork (genre)","Juke":"Juke (genre)","Phonk":"Phonk",
"Americana":"Americana (music)","Bluegrass":"Bluegrass music","Old-time":"Old-time music",
"Cajun":"Cajun music","Zydeco":"Zydeco","Celtic":"Celtic music","Medieval":"Medieval music",
"Renaissance":"Renaissance music",
}
